- Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [18]:
import numpy as np
def resum_estadistic (arr):
    print ("Mitjana:", (np.mean (arr)))
    print ("Media:", (np.median(arr)))
    print ("Coeficient de correlació:", (np.corrcoef(arr)))
    print ("Desviació estàndard:", (np.std(arr)))
x= [2,4,5,3]
arr =np.array (x)
dimensions= arr.ndim
if dimensions > 1:
    print ("error")
else:
    resum_estadistic (arr)

Mitjana: 3.5
Media: 3.5
Coeficient de correlació: 1.0
Desviació estàndard: 1.118033988749895


- Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100

In [20]:
arr_random_q= np.random.randint(100, size=(4,4))
print (arr_random_q)

[[26 24 94 74]
 [ 5  2 88  0]
 [60 14 62 95]
 [18 65 72 63]]


- Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [21]:
arr_random_r= np.random.randint (100, size= (5,4))
#print (arr_random_r)
x = arr_random_r
def total_files_i_columnes(x):
    suma_columnes= np.sum (x, axis=0)
    print (suma_columnes)
    suma_files= np.sum (x, axis=1)
    print (suma_files)
total_files_i_columnes (arr_random_r)

[237 206 182 311]
[232 265 101 195 143]


- Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [22]:
import numpy as np
alçades = [178, 182, 190, 152, 122]
pesos = [73, 77,83, 60, 50]
mitja_alçades = np.mean (alçades)
mitja_pesos = np.mean (pesos)
distancia_alçades = alçades - mitja_alçades
distancia_pesos = pesos - mitja_pesos
numerador = np.sum (distancia_alçades * distancia_pesos)
#print (mitja_alçades)
#print (numerador)
#print (distancia_alçades)
#print (distancia_pesos)
distancia_alçadesq = np.square (distancia_alçades)
distancia_pesosq = np.square (distancia_pesos)
#print (distancia_alçadesq)
#print (distancia_pesosq)
sum_distancia_alçadesq =np.sum (distancia_alçadesq)
#print (sum_distancia_alçadesq)
sum_distancia_pesosq = np.sum (distancia_pesosq)
#print (sum_distancia_pesosq)
mult_sdpq_sdaq = sum_distancia_alçadesq * sum_distancia_pesosq
#print (mult_sdpq_sdaq)
denominador = np.sqrt (mult_sdpq_sdaq)
#print (denominador)
coeficient_correlació = numerador / denominador
print ("Coeficient de correlació és",coeficient_correlació)

Coeficient de correlació és 0.9868082258449881
